// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billno.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.billno;

public final class BillnoPb {
  private BillnoPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBillnoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seezoon.billno.GetBillnoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 非空
     * </pre>
     *
     * <code>string biz_code = 1;</code>
     * @return The bizCode.
     */
    java.lang.String getBizCode();
    /**
     * <pre>
     * 非空
     * </pre>
     *
     * <code>string biz_code = 1;</code>
     * @return The bytes for bizCode.
     */
    com.google.protobuf.ByteString
        getBizCodeBytes();
  }
  /**
   * Protobuf type {@code com.seezoon.billno.GetBillnoReq}
   */
  public static final class GetBillnoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seezoon.billno.GetBillnoReq)
      GetBillnoReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetBillnoReq.newBuilder() to construct.
    private GetBillnoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBillnoReq() {
      bizCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetBillnoReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seezoon.stub.billno.BillnoPb.GetBillnoReq.class, com.seezoon.stub.billno.BillnoPb.GetBillnoReq.Builder.class);
    }

    public static final int BIZ_CODE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bizCode_ = "";
    /**
     * <pre>
     * 非空
     * </pre>
     *
     * <code>string biz_code = 1;</code>
     * @return The bizCode.
     */
    @java.lang.Override
    public java.lang.String getBizCode() {
      java.lang.Object ref = bizCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bizCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 非空
     * </pre>
     *
     * <code>string biz_code = 1;</code>
     * @return The bytes for bizCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBizCodeBytes() {
      java.lang.Object ref = bizCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bizCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bizCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bizCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bizCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bizCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seezoon.stub.billno.BillnoPb.GetBillnoReq)) {
        return super.equals(obj);
      }
      com.seezoon.stub.billno.BillnoPb.GetBillnoReq other = (com.seezoon.stub.billno.BillnoPb.GetBillnoReq) obj;

      if (!getBizCode()
          .equals(other.getBizCode())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BIZ_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getBizCode().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seezoon.stub.billno.BillnoPb.GetBillnoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seezoon.billno.GetBillnoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seezoon.billno.GetBillnoReq)
        com.seezoon.stub.billno.BillnoPb.GetBillnoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seezoon.stub.billno.BillnoPb.GetBillnoReq.class, com.seezoon.stub.billno.BillnoPb.GetBillnoReq.Builder.class);
      }

      // Construct using com.seezoon.stub.billno.BillnoPb.GetBillnoReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bizCode_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoReq_descriptor;
      }

      @java.lang.Override
      public com.seezoon.stub.billno.BillnoPb.GetBillnoReq getDefaultInstanceForType() {
        return com.seezoon.stub.billno.BillnoPb.GetBillnoReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.seezoon.stub.billno.BillnoPb.GetBillnoReq build() {
        com.seezoon.stub.billno.BillnoPb.GetBillnoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seezoon.stub.billno.BillnoPb.GetBillnoReq buildPartial() {
        com.seezoon.stub.billno.BillnoPb.GetBillnoReq result = new com.seezoon.stub.billno.BillnoPb.GetBillnoReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.seezoon.stub.billno.BillnoPb.GetBillnoReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bizCode_ = bizCode_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seezoon.stub.billno.BillnoPb.GetBillnoReq) {
          return mergeFrom((com.seezoon.stub.billno.BillnoPb.GetBillnoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seezoon.stub.billno.BillnoPb.GetBillnoReq other) {
        if (other == com.seezoon.stub.billno.BillnoPb.GetBillnoReq.getDefaultInstance()) return this;
        if (!other.getBizCode().isEmpty()) {
          bizCode_ = other.bizCode_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                bizCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object bizCode_ = "";
      /**
       * <pre>
       * 非空
       * </pre>
       *
       * <code>string biz_code = 1;</code>
       * @return The bizCode.
       */
      public java.lang.String getBizCode() {
        java.lang.Object ref = bizCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bizCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 非空
       * </pre>
       *
       * <code>string biz_code = 1;</code>
       * @return The bytes for bizCode.
       */
      public com.google.protobuf.ByteString
          getBizCodeBytes() {
        java.lang.Object ref = bizCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bizCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 非空
       * </pre>
       *
       * <code>string biz_code = 1;</code>
       * @param value The bizCode to set.
       * @return This builder for chaining.
       */
      public Builder setBizCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bizCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 非空
       * </pre>
       *
       * <code>string biz_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBizCode() {
        bizCode_ = getDefaultInstance().getBizCode();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 非空
       * </pre>
       *
       * <code>string biz_code = 1;</code>
       * @param value The bytes for bizCode to set.
       * @return This builder for chaining.
       */
      public Builder setBizCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bizCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seezoon.billno.GetBillnoReq)
    }

    // @@protoc_insertion_point(class_scope:com.seezoon.billno.GetBillnoReq)
    private static final com.seezoon.stub.billno.BillnoPb.GetBillnoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seezoon.stub.billno.BillnoPb.GetBillnoReq();
    }

    public static com.seezoon.stub.billno.BillnoPb.GetBillnoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBillnoReq>
        PARSER = new com.google.protobuf.AbstractParser<GetBillnoReq>() {
      @java.lang.Override
      public GetBillnoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetBillnoReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetBillnoReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seezoon.stub.billno.BillnoPb.GetBillnoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetBillnoRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seezoon.billno.GetBillnoResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 err_code = 1;</code>
     * @return The errCode.
     */
    int getErrCode();

    /**
     * <code>string err_msg = 2;</code>
     * @return The errMsg.
     */
    java.lang.String getErrMsg();
    /**
     * <code>string err_msg = 2;</code>
     * @return The bytes for errMsg.
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    /**
     * <code>uint64 billno = 3;</code>
     * @return The billno.
     */
    long getBillno();
  }
  /**
   * Protobuf type {@code com.seezoon.billno.GetBillnoResp}
   */
  public static final class GetBillnoResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.seezoon.billno.GetBillnoResp)
      GetBillnoRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetBillnoResp.newBuilder() to construct.
    private GetBillnoResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBillnoResp() {
      errMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetBillnoResp();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seezoon.stub.billno.BillnoPb.GetBillnoResp.class, com.seezoon.stub.billno.BillnoPb.GetBillnoResp.Builder.class);
    }

    public static final int ERR_CODE_FIELD_NUMBER = 1;
    private int errCode_ = 0;
    /**
     * <code>int32 err_code = 1;</code>
     * @return The errCode.
     */
    @java.lang.Override
    public int getErrCode() {
      return errCode_;
    }

    public static final int ERR_MSG_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object errMsg_ = "";
    /**
     * <code>string err_msg = 2;</code>
     * @return The errMsg.
     */
    @java.lang.Override
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string err_msg = 2;</code>
     * @return The bytes for errMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BILLNO_FIELD_NUMBER = 3;
    private long billno_ = 0L;
    /**
     * <code>uint64 billno = 3;</code>
     * @return The billno.
     */
    @java.lang.Override
    public long getBillno() {
      return billno_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errCode_ != 0) {
        output.writeInt32(1, errCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errMsg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMsg_);
      }
      if (billno_ != 0L) {
        output.writeUInt64(3, billno_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errMsg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMsg_);
      }
      if (billno_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, billno_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seezoon.stub.billno.BillnoPb.GetBillnoResp)) {
        return super.equals(obj);
      }
      com.seezoon.stub.billno.BillnoPb.GetBillnoResp other = (com.seezoon.stub.billno.BillnoPb.GetBillnoResp) obj;

      if (getErrCode()
          != other.getErrCode()) return false;
      if (!getErrMsg()
          .equals(other.getErrMsg())) return false;
      if (getBillno()
          != other.getBillno()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERR_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrCode();
      hash = (37 * hash) + ERR_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrMsg().hashCode();
      hash = (37 * hash) + BILLNO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBillno());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seezoon.stub.billno.BillnoPb.GetBillnoResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seezoon.billno.GetBillnoResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seezoon.billno.GetBillnoResp)
        com.seezoon.stub.billno.BillnoPb.GetBillnoRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seezoon.stub.billno.BillnoPb.GetBillnoResp.class, com.seezoon.stub.billno.BillnoPb.GetBillnoResp.Builder.class);
      }

      // Construct using com.seezoon.stub.billno.BillnoPb.GetBillnoResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        errCode_ = 0;
        errMsg_ = "";
        billno_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seezoon.stub.billno.BillnoPb.internal_static_com_seezoon_billno_GetBillnoResp_descriptor;
      }

      @java.lang.Override
      public com.seezoon.stub.billno.BillnoPb.GetBillnoResp getDefaultInstanceForType() {
        return com.seezoon.stub.billno.BillnoPb.GetBillnoResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.seezoon.stub.billno.BillnoPb.GetBillnoResp build() {
        com.seezoon.stub.billno.BillnoPb.GetBillnoResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seezoon.stub.billno.BillnoPb.GetBillnoResp buildPartial() {
        com.seezoon.stub.billno.BillnoPb.GetBillnoResp result = new com.seezoon.stub.billno.BillnoPb.GetBillnoResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.seezoon.stub.billno.BillnoPb.GetBillnoResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.errCode_ = errCode_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.errMsg_ = errMsg_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.billno_ = billno_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seezoon.stub.billno.BillnoPb.GetBillnoResp) {
          return mergeFrom((com.seezoon.stub.billno.BillnoPb.GetBillnoResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seezoon.stub.billno.BillnoPb.GetBillnoResp other) {
        if (other == com.seezoon.stub.billno.BillnoPb.GetBillnoResp.getDefaultInstance()) return this;
        if (other.getErrCode() != 0) {
          setErrCode(other.getErrCode());
        }
        if (!other.getErrMsg().isEmpty()) {
          errMsg_ = other.errMsg_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getBillno() != 0L) {
          setBillno(other.getBillno());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                errCode_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                errMsg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                billno_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int errCode_ ;
      /**
       * <code>int32 err_code = 1;</code>
       * @return The errCode.
       */
      @java.lang.Override
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>int32 err_code = 1;</code>
       * @param value The errCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrCode(int value) {

        errCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 err_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>string err_msg = 2;</code>
       * @return The errMsg.
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string err_msg = 2;</code>
       * @return The bytes for errMsg.
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string err_msg = 2;</code>
       * @param value The errMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        errMsg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string err_msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrMsg() {
        errMsg_ = getDefaultInstance().getErrMsg();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string err_msg = 2;</code>
       * @param value The bytes for errMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        errMsg_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long billno_ ;
      /**
       * <code>uint64 billno = 3;</code>
       * @return The billno.
       */
      @java.lang.Override
      public long getBillno() {
        return billno_;
      }
      /**
       * <code>uint64 billno = 3;</code>
       * @param value The billno to set.
       * @return This builder for chaining.
       */
      public Builder setBillno(long value) {

        billno_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 billno = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBillno() {
        bitField0_ = (bitField0_ & ~0x00000004);
        billno_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.seezoon.billno.GetBillnoResp)
    }

    // @@protoc_insertion_point(class_scope:com.seezoon.billno.GetBillnoResp)
    private static final com.seezoon.stub.billno.BillnoPb.GetBillnoResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seezoon.stub.billno.BillnoPb.GetBillnoResp();
    }

    public static com.seezoon.stub.billno.BillnoPb.GetBillnoResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBillnoResp>
        PARSER = new com.google.protobuf.AbstractParser<GetBillnoResp>() {
      @java.lang.Override
      public GetBillnoResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetBillnoResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetBillnoResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seezoon.stub.billno.BillnoPb.GetBillnoResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_billno_GetBillnoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_billno_GetBillnoReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_billno_GetBillnoResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_billno_GetBillnoResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014billno.proto\022\022com.seezoon.billno\" \n\014Ge" +
      "tBillnoReq\022\020\n\010biz_code\030\001 \001(\t\"B\n\rGetBilln" +
      "oResp\022\020\n\010err_code\030\001 \001(\005\022\017\n\007err_msg\030\002 \001(\t" +
      "\022\016\n\006billno\030\003 \001(\0042\\\n\006Billno\022R\n\tGetBillno\022" +
      " .com.seezoon.billno.GetBillnoReq\032!.com." +
      "seezoon.billno.GetBillnoResp\"\000BW\n\027com.se" +
      "ezoon.stub.billnoB\010BillnoPbP\000Z0github.co" +
      "m/seezoon-go-stub/billno-server-stub;pbb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_seezoon_billno_GetBillnoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_seezoon_billno_GetBillnoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_billno_GetBillnoReq_descriptor,
        new java.lang.String[] { "BizCode", });
    internal_static_com_seezoon_billno_GetBillnoResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_seezoon_billno_GetBillnoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_billno_GetBillnoResp_descriptor,
        new java.lang.String[] { "ErrCode", "ErrMsg", "Billno", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
